### PR TITLE
Update Icon

### PR DESCRIPTION
**Pull request by n-ce**

### CODE REVIEW

**Comment by wmartinmimi** [comment]
The pull request seems fine, and the logo looks cool. The use of pure white to make both a logo and notification icon is very smart. But I think I have 2 concerns for this.

1. How well would its visibility be against a white/light wallpaper? I have a concern that people can't find it due to the low contrast. There is also a white coloured "share to..." dialogue in light mode too.

2. Not as important, but I'm not sure if people will think of music player on first glance, although I could change it a bit and it can look more like a headphone. There are a lot of logo out there that doesn't make sense though, to be fair.

**Comment by n-ce** [comment]
how about these?
pixil-frame-0 (5)-min
maskable_icon-min

**Comment by wmartinmimi** [comment]
I created these during the day, would you consider these?





It resembles a headphone, and does so in a clear, minimal way. It is also a lot smaller than the original icons.

**Comment by n-ce** [comment]
its really perfect! Just the background color , change it to some cool colors, this is to distinct between tiny and little.

**Comment by wmartinmimi** [comment]
I created these during the day, would you consider these?





It resembles a headphone, and does so in a clear, minimal way. It is also a lot smaller than the original icons.

**Comment by wmartinmimi** [comment]
I created these during the day, would you consider these?





It resembles a headphone, and does so in a clear, minimal way. It is also a lot smaller than the original icons.

**Comment by n-ce** [comment]
That will do!

**Pull request closed without merging**
